version: '3'

services:
  snippet-infra-api:
    container_name: "snippet-infra-api"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8083:8083"
    environment:
      DB_USER: sa
      DB_PASSWORD: password
      DB_NAME: compose-db
      DB_HOST: snippet_infra_db
      DB_PORT: 5432

  snippet_infra_db:
    container_name: snippet_infra_db
    image: postgres:12
    ports:
      - "5435:5435"
    environment:
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: password
      POSTGRES_DB: compose-db