version: '3'

services:
  proxy:
      container_name: "reverse-proxy"
      image: nginx
      ports:
        - "80:80"
        - "443:443"
      volumes:
        - ./conf.d:/etc/nginx/conf.d:ro
#        - ./certbot/conf:/etc/letsencrypt
#        - ./certbot/www:/var/www/certbot
      depends_on:
        - snippet-share
        - snippet-share-db
        - snippet-manager
        - snippet-manager-db
        - snippet-runner


  datadog:
    image: datadog/agent
    container_name: "datadog-dev-env"
    environment:
      - DD_API_KEY=${DD_API_KEY}
      - DD_SITE=us5.datadoghq.com
      - DD_LOGS_ENABLED=true
      - DD_APM_ENABLED=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup:/host/sys/fs/cgroup:ro


  snippet-share:
    image: ghcr.io/ingsis-group-6/snippet-share-dev:latest
    environment:
      DD_API_KEY: ${DD_API_KEY}
      DB_HOST: snippet-share-db
      DB_PORT: 5433
      DB_NAME: snippet-share-db
      DB_USER: postgres
      DB_PASSWORD: pablo
    labels:
      com.datadoghq.ad.logs: '[{"source": "java", "service": "snippet-share-dev", "log_processing_rules": [{"type": "multi_line", "name": "log_start_with_date", "pattern" : "\\d{4}-(0?[1-9]|1[012])-(0?[1-9]|[12][0-9]|3[01])"}]}]'
    depends_on:
      - snippet-share-db

  snippet-share-db:
    container_name: snippet-share-db
    image: postgres:alpine
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pablo
      POSTGRES_DB: snippet-share-db
    command: -p 5433

  redis:
    container_name: "redis"
    image: redis:6-alpine
    ports:
      - "6379:6379"

  snippet-manager:
    image: ghcr.io/ingsis-group-6/snippet-manager-dev:latest
    environment:
      DD_API_KEY: ${DD_API_KEY}
      DB_HOST: snippet-manager-db
      DB_PORT: 5434
      DB_NAME: snippet-manager-db
      DB_USER: postgres
      DB_PASSWORD: pablo
      REDIS_STREAM_KEY: ingsis-group-6
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_STREAM_GROUP_LINT: lint-manager

    labels:
      com.datadoghq.ad.logs: '[{"source": "java", "service": "snippet-manager-dev", "log_processing_rules": [{"type": "multi_line", "name": "log_start_with_date", "pattern" : "\\d{4}-(0?[1-9]|1[012])-(0?[1-9]|[12][0-9]|3[01])"}]}]'
    depends_on:
      - snippet-manager-db

  snippet-manager-db:
    container_name: snippet-manager-db
    image: postgres:alpine
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pablo
      POSTGRES_DB: snippet-manager-db
    command: -p 5434


  snippet-runner:
    image: ghcr.io/ingsis-group-6/snippet-runner-dev:latest
    environment:
      DD_API_KEY: ${DD_API_KEY}
      REDIS_STREAM_KEY: ingsis-group-6
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_STREAM_GROUP_LINT: lint-manager

    labels:
      com.datadoghq.ad.logs: '[{"source": "java", "service": "snippet-runner-dev", "log_processing_rules": [{"type": "multi_line", "name": "log_start_with_date", "pattern" : "\\d{4}-(0?[1-9]|1[012])-(0?[1-9]|[12][0-9]|3[01])"}]}]'




  #  certbot:
  #    image: certbot/certbot
  #    container_name: certbot
  #    volumes:
  #      - ./certbot/conf:/etc/letsencrypt
  #      - ./certbot/www:/var/www/certbot
  #    command: certonly --webroot -w /var/www/certbot --force-renewal --email ricardo.lopez@ing.austral.edu.ar -d ingsisgroup6dev.gleeze.com --agree-tos


  # snippet-infra-api:
  #   container_name: "snippet-infra-api"
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #     - "8083:8083"
  #   environment:
  #     DB_USER: sa
  #     DB_PASSWORD: password
  #     DB_NAME: compose-db
  #     DB_HOST: snippet_infra_db
  #     DB_PORT: 5432
