version: '3'

services:
  # snippet-infra-api:
  #   container_name: "snippet-infra-api"
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #     - "8083:8083"
  #   environment:
  #     DB_USER: sa
  #     DB_PASSWORD: password
  #     DB_NAME: compose-db
  #     DB_HOST: snippet_infra_db
  #     DB_PORT: 5432


  snippet-api:
    image: ghcr.io/ingsis-group-6/snippet-api:latest
#    ports:
#      - "8080:8080"
    environment:
      DB_USER: sa
      DB_PASSWORD: password
      DB_NAME: compose-db
      DB_HOST: snippet_manager_db
      DB_PORT: 5432

  snippet-manager:
      image: ghcr.io/ingsis-group-6/snippet-manager:latest
#      ports:
#        - "8081:8080"
      environment:
        DB_USER: sa
        DB_PASSWORD: password
        DB_NAME: compose-db
        DB_HOST: snippet_manager_db
        DB_PORT: 5432

  snippet-runner:
    image: ghcr.io/ingsis-group-6/snippet-runner:latest
#    ports:
#      - "8082:8080"
    environment:
      DB_USER: sa
      DB_PASSWORD: password
      DB_NAME: compose-db
      DB_HOST: snippet_manager_db
      DB_PORT: 5432

  snippet-share:
    image: ghcr.io/ingsis-group-6/snippet-share:latest
#    ports:
#      - "8083:8080"
    environment:
      DB_USER: sa
      DB_PASSWORD: password
      DB_NAME: compose-db
      DB_HOST: snippet_manager_db
      DB_PORT: 5432

  proxy:
    container_name: "reverse-proxy"
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./conf.d:/etc/nginx/conf.d:ro
  my-server:
    container_name: "my-server"
    build: ./server

  # snippet_infra_db:
  #   container_name: snippet_infra_db
  #   image: postgres:12
  #   ports:
  #     - "5435:5435"
  #   environment:
  #     POSTGRES_USER: sa
  #     POSTGRES_PASSWORD: password
  #     POSTGRES_DB: compose-db