version: '3'

services:
  proxy:
      container_name: "reverse-proxy"
      image: nginx
      ports:
        - "80:80"
      volumes:
        - ./conf.d:/etc/nginx/conf.d:ro
  # snippet-infra-api:
  #   container_name: "snippet-infra-api"
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #     - "8083:8083"
  #   environment:
  #     DB_USER: sa
  #     DB_PASSWORD: password
  #     DB_NAME: compose-db
  #     DB_HOST: snippet_infra_db
  #     DB_PORT: 5432


#   snippet-api:
#     image: ghcr.io/ingsis-group-6/snippet-api:latest
# #    ports:
# #      - "8080:8080"
#     environment:
#       DB_USER: sa
#       DB_PASSWORD: password
#       DB_NAME: compose-db
#       DB_HOST: snippet_manager_db
#       DB_PORT: 5432

  snippet-manager:
      container_name: "manager-dev-env"
      image: ghcr.io/ingsis-group-6/snippet-manager:latest
#      ports:
#        - "8081:8080"
      environment:
        DD_API_KEY: ${DD_API_KEY}
        DB_USER: sa
        DB_PASSWORD: password
        DB_NAME: compose-db
        DB_HOST: snippet_manager_db
        DB_PORT: 5432
      labels:
          com.datadoghq.ad.logs: '[{"source": "java", "service": "manager-api-dev", "log_processing_rules": [{"type": "multi_line", "name": "log_start_with_date", "pattern" : "\\d{4}-(0?[1-9]|1[012])-(0?[1-9]|[12][0-9]|3[01])"}]}]'

  snippet-runner:
    image: ghcr.io/ingsis-group-6/snippet-runner-dev:latest
#    ports:
#      - "8082:8080"
    environment:
      DB_USER: sa
      DB_PASSWORD: password
      DB_NAME: compose-db
      DB_HOST: snippet_manager_db
      DB_PORT: 5432

  snippet-share:
    image: ghcr.io/ingsis-group-6/snippet-share-dev:latest
#    ports:
#      - "8083:8080"
    environment:
      DB_USER: sa
      DB_PASSWORD: password
      DB_NAME: snippet-share-db
      DB_HOST: snippet-share-db
      DB_PORT: 5433

  
#  my-server:
#    container_name: "my-server"
#    build: ./server

  snippet-share-db:
    container_name: snippet-share-db
    image: postgres:12
    ports:
      - "5433:5433"
    environment:
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: password
      POSTGRES_DB: snippet-share-db
    command: -p 5433
