version: '3'

services:
  proxy:
      container_name: "reverse-proxy"
      image: nginx
      ports:
        - "80:80"
        - "443:443"
      volumes:
        - ./conf.d:/etc/nginx/conf.d:ro
#        - ./certbot/conf:/etc/letsencrypt
#        - ./certbot/www:/var/www/certbot


#  snippet-manager:
#      image: ghcr.io/ingsis-group-6/snippet-manager:latest
#      environment:
#        DB_USER: sa
#        DB_PASSWORD: password
#        DB_NAME: compose-db
#        DB_HOST: snippet_manager_db
#        DB_PORT: 5432
#
#  snippet-manager-db:
#    container_name: snippet-share-db
#    image: postgres:12
#    ports:
#      - "5433:5433"
#    environment:
#      POSTGRES_USER: sa
#      POSTGRES_PASSWORD: password
#      POSTGRES_DB: snippet-share-db
#    command: -p 5433
#
#  snippet-runner:
#    image: ghcr.io/ingsis-group-6/snippet-runner:latest
#    environment:
#      DB_USER: sa
#      DB_PASSWORD: password
#      DB_NAME: compose-db
#      DB_HOST: snippet_manager_db
#      DB_PORT: 5432



  snippet-share:
    image: ghcr.io/ingsis-group-6/snippet-share:latest
    environment:
      DD_API_KEY: ${DD_API_KEY}
      DB_HOST: snippet-share-db
      DB_PORT: 5433
      DB_NAME: snippet-share-db
      DB_USER: postgres
      DB_PASSWORD: pablo

  snippet-share-db:
    container_name: snippet-share-db
    image: postgres:12
    ports:
      - "5433:5433"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pablo
      POSTGRES_DB: snippet-share-db
    command: -p 5433








  #  certbot:
  #    image: certbot/certbot
  #    container_name: certbot
  #    volumes:
  #      - ./certbot/conf:/etc/letsencrypt
  #      - ./certbot/www:/var/www/certbot
  #    command: certonly --webroot -w /var/www/certbot --force-renewal --email ricardo.lopez@ing.austral.edu.ar -d ingsisgroup6dev.gleeze.com --agree-tos


  # snippet-infra-api:
  #   container_name: "snippet-infra-api"
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #     - "8083:8083"
  #   environment:
  #     DB_USER: sa
  #     DB_PASSWORD: password
  #     DB_NAME: compose-db
  #     DB_HOST: snippet_infra_db
  #     DB_PORT: 5432
